### ISSUE TITLE
Add Resource Request and Limit to the Container

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6600]
## Overview of feature request
We should be able to add Resource Request and Limit for a Container. This is also important because by setting these we could make sure that the Pod gets the right [QoS class](https://kubernetes.io/docs/concepts/workloads/pods/pod-qos/). There are 3 QoS classes: **Guaranteed**, **Burstable**, and **BestEffort**. For a Radius user that has multiple Pods, setting this through Resource Requests and Limits might be important for making a priority list of Pods.

```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  namespace: qos-example
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
```
Example is from here: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/.

## Acceptance criteria
You can find an example of Resource Requests and Limits here: https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/.

## Additional context

[AB#9968](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9968)
