### ISSUE TITLE
Add securityContext support for a Container

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6643]
## Overview of feature request
We should add support for specifying the **security context** for a Container.

Important ones might be but not limited to:
1. runAsUser
2. runAsNonRoot

Example:
```
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  volumes:
  - name: sec-ctx-vol
    emptyDir: {}
  containers:
  - name: sec-ctx-demo
    image: busybox:1.28
    command: [ "sh", "-c", "sleep 1h" ]
    volumeMounts:
    - name: sec-ctx-vol
      mountPath: /data/demo
    securityContext:
      allowPrivilegeEscalation: false
```

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://yuminlee2.medium.com/kubernetes-security-contexts-e54624e29d52

## Acceptance criteria
The user should be able to set the security context for a container.
