### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jasonviviano** [radius-project/radius#6884]
## Bug information
Trying to consume a `manifest.yaml` and deploy a Radius Application with Bicep.

### Steps to reproduce (required)

1. Manifest.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice # Required for Radius validation
  labels:
    app: my-microservice # Radius will perform a synthetic validation but a hard requirement
spec:
  selector:
  template:
    spec:
      containers:
        - name: my-microservice
```
2. Bicep file
```
import radius as radius

resource app 'Applications.Core/applications@2023-10-01-preview' = {
  name: 'ktest'
}

resource container 'Applications.Core/containers@2023-10-01-preview' = {
  name: 'demo'
  properties: {
    application: app.id
    container: {}
    runtimes: {
      kubernetes: {
        base: loadTextContent('./manifest.yaml')
      }
    }
  }
}

```
3. Run `rad deploy ./test.bicep`
Console output:

```
Building test.bicep...
/workspaces/samples/test.bicep(11,5) : Warning BCP035: The specified "object" declaration is missing the following required properties: "image". If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
Deploying template 'test.bicep' into environment 'default' from workspace 'default'...

Deployment In Progress...

...                  ktest           Applications.Core/applications
Error: {
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please see the details for the specific operation that failed.",
  "target": "/planes/radius/local/resourceGroups/default/providers/Microsoft.Resources/deployments/rad-deploy-f2b7fc0f-41b3-4812-b790-6e8752455295",
  "details": [
    {
      "code": "Internal",
      "message": "unexpected error: runtime error: invalid memory address or nil pointer dereference",
      "target": "/planes/radius/local/resourceGroups/default/providers/Applications.Core/applications/ktest"
    }
  ]
}

TraceId:  593dc7810bf264812f5e345583dbb560
```
### rad Version (required)

```
RELEASE   VERSION   BICEP     COMMIT
0.27.1    v0.27.1   0.27.1    a0fa10b71c2517934cbea90ddb87486f55652f82
```
### Operating system (required)
Codespace

## Additional context

[AB#10596](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10596)
