### ISSUE TITLE
Deleting a user defined resource provider makes `rad env list` fail with bad request

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/radius#9149]
### Steps to reproduce

1. Create a resource type in Radius using ` rad resource-type create postgreSQL -f postgreSQL.yaml`

Contents of `postgreSQL.yaml` are below

```
name: MyCompany.Resources
types:
  postgreSQL:
    apiVersions:
      '2023-10-01-preview':
        schema: 
          type: object
          properties:
            environment:
              type: string
            status:
              type: object
              properties:
                binding:
                  type: object
                  properties:
                    database:
                      type: string
                      description: The name of the database.
                    host:
                      type: string
                      description: The host name of the database.
                    port:
                      type: string
                      description: The port number of the database.
                    username:
                      type: string
                      description: The username for the database.
                    password:
                      type: string
                      description: The password for the database.
    capabilities: ["SupportsRecipes"]
```
2. Delete the resource-provider `MyCompany.Resources` using `rad resource-provider delete MyCompany.Resources`
3. List the environments using `rad env list` 
    

### Observed behavior

`rad env list` fails on the below error

```
Error: {
  "code": "BadRequest",
  "message": "resource type \"Applications.Core/environments\" not found",
  "target": "/planes/radius/local/resourcegroups/default/providers/Applications.Core/environments"
}
```
Also other CLI commands that operates on Application.Core resource types fails with the same error

### Desired behavior

`rad env list` should not fail 

### Workaround

On restarting the cluster, the error goes away and `rad env list` lists the environment

### rad Version

RELEASE   VERSION   BICEP     COMMIT
edge      93dd477   0.34.44   93dd47793811e08a6a05c328368f06177f9f7b6f

### Operating system

MacOS M1 chip

### Additional context

Cluster info - k3d 

@nithyatsu was able to replicate this issue with Radius v0.44 

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by AzureMike** [comment]
## Updated reproduction and confirmed scope

Deleting a custom resource provider also deletes resource-type and location registrations belonging to unrelated providers, including built-in Radius providers. Their provider records remain, but their registered types and locations are empty.

As a result, ordinary operations such as creating a Radius environment fail with "resource type is not registered". A routine cleanup command can therefore break resource operations across the Radius installation.

## Steps to reproduce

**Use a disposable Radius installation only. This reproduction removes registrations used by unrelated applications. Do not run it against a shared cluster.**

Use a configured Radius workspace and an existing resource group. No recipe or deployed custom-resource instance is required.

Save this as `delete-provider.yaml`:

```yaml
namespace: Repro.DeleteMe
types:
  objects:
    apiVersions:
      2023-10-01-preview:
        schema:
          type: object
```

1. Register the temporary type and inspect an unrelated built-in provider:

   ```sh
   rad resource-type create --from-file delete-provider.yaml
   rad resource-provider show Applications.Core -o json
   ```

   Confirm that `resourceTypes` includes `environments` and `locations` includes `global`.

2. Delete only the temporary provider:

   ```sh
   rad resource-provider delete Repro.DeleteMe --yes
   ```

3. Inspect the unrelated provider again:

   ```sh
   rad resource-provider show Applications.Core -o json
   ```

   Its record still exists, but now contains:

   ```json
   {
     "locations": {},
     "name": "Applications.Core",
     "resourceTypes": {}
   }
   ```

4. Try a normal environment creation in the existing group:

   ```sh
   rad env create after-provider-delete --kubernetes-namespace after-provider-delete
   ```

   It fails with `BadRequest`:

   ```text
   resource type "Applications.Core/environments" is not registered. register the resource type before deploying resources of this type
   ```

## Expected behavior

Deleting `Repro.DeleteMe` should remove only that provider and its registrations. Other providers' types and locations should remain unchanged, and environment creation should continue to work.

## Verified scope

Before deletion, the disposable installation had 36 resource types and 12 locations across its built-in providers. Deleting `Repro.DeleteMe` removed those registrations and those of another custom provider, `Repro.ConfigMaps`. Direct GETs for the unrelated `Applications.Core/environments` registration and `Applications.Core/locations/global` returned `404`.

The existing recipe-created ConfigMaps remained with their original UIDs. This test establishes deletion of control-plane registrations and broken resource operations, not deletion of the backing workloads.

## Technical context

Before deletion, the provider-specific child-list endpoints for `Repro.DeleteMe` returned entries from other providers: 38 resource types and 14 locations, rather than its own one type and one location.

The [resource-provider delete controller](https://github.com/radius-project/radius/blob/f2f2e9f72df5d16180741f8763203e1d005d643d/pkg/ucp/backend/controller/resourceproviders/resourceprovider_delete.go) deletes every location and resource type returned by those lists. UCP logs tied deletions under `Applications.Core`, `Radius.Core`, and other providers to the single delete operation for `Repro.DeleteMe`.

The [child-list routes](https://github.com/radius-project/radius/blob/f2f2e9f72df5d16180741f8763203e1d005d643d/pkg/ucp/frontend/radius/routes.go#L289-L293) use [`ListResources`](https://github.com/radius-project/radius/blob/f2f2e9f72df5d16180741f8763203e1d005d643d/pkg/armrpc/frontend/defaultoperation/listresources.go#L49-L57), whose database query includes the root scope and resource type but not the parent provider ID.

Reproduced twice on disposable Kubernetes installations using CLI `v0.60.2` and `ucpd:0.60` with image digest `sha256:b4bb1b239d213a21a77d24e581b824dcae23965776cd313383d33435d2a219db`. The code links identify the separately inspected source revision.
