### ISSUE TITLE
`rad resource-type create` to create all resource-types defined in the `yaml`

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/radius#9158]
### Overview of feature request

Today `rad resource-type create` can create only one resource-type at a time from the `yaml` If the user has multiple resource-types defined, they have to run the `rad resource-type create` for each of the resource type. There should be an easy option to add all the resource types defined in the `yaml` in one go.

**Current experience**
Example resource type definition:

```yaml
name: MyCompany.Resources
types:
  resourcetype1:
    apiVersions:
       '2023-10-01-preview':
         schema: 
 resourcetype2:
    apiVersions:
       '2023-10-01-preview':
           schema:
```
In order to create all resource-types user has to do 
1. rad resource-type create resourcetype1 -f test.yaml
2. rad resource-type create resourcetype2 -f test.yaml

**Proposed experience**
`rad resource-type create -f test.yaml` should create all resource-types defined under a namespace in the `yaml` file.

### Acceptance criteria

`rad resource-type create -f test.yaml` should create all resource-types defined under a namespace in the `yaml` file.

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#15425](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/15425)
