### ISSUE TITLE
Support array of strings in resource type definition

### ISSUE THREAD

**Issue by zachcasper** [radius-project/radius#9365]
### Steps to reproduce

When defining a resource type, I need a property which is an array of strings. For example, if I was modeling a container which may take multiple arguments:
```
name: Hollow.Core
types:
  containers:
    # This will not be required in the future since it is the default.
    capabilities: ["SupportsRecipes"]
    apiVersions:
      # The only API version supported is 2023-10-01-preview. See https://github.com/radius-project/radius/issues/9357
      '2023-10-01-preview':
        schema: 
          type: object
          properties:
            ...
            container:
              type: object
              properties:
                ...
                args:
                  type: array
                  description: "Optional: Array of strings; arguments passed to the container's command; for example 	['-c', 'while true; do echo hello; sleep 10; done']"
                  items:
                    type: string
```
Radius does not like `array`.
```
rad bicep publish-extension -f types.yaml --target hollowcore.tgz
Failed to read resource provider "types.yaml" Cause: [38:190] value is not allowed in this context. map key-value is pre-defined
  35 |                   #   type: string
  36 |                 args:
  37 |                   type: array
> 38 |                   description: "Optional: Array of strings; arguments passed to the container's command; for example     ['-c', 'while true; do echo hello; sleep 10; done']"                  items:
                                                                                                                                                                                                    ^
  39 |                     type: string
  40 |                 workingDir:
  41 |                   type: string
  42 |.
```

### Desired behavior

```
                args:
                  type: array
                  description: "Optional: Array of strings; arguments passed to the container's command; for example 	['-c', 'while true; do echo hello; sleep 10; done']"
                  items:
                    type: string
```
should work.

### rad Version

0.46

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#15660](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/15660)
