### ISSUE TITLE
Feature request: Least privileged Kubernetes role definition

### ISSUE THREAD

**Issue by zachcasper** [radius-project/radius#9448]
### Overview of feature request

In a multi-user environment, a Radius user should not have access to any other resources on the Kubernetes cluster.

Note: This is not Radius RBAC, but rather only the Kubernetes user. Radius RBAC is addressed in https://github.com/radius-project/design-notes/blob/main/architecture/2024-11-authz-feature-spec.md

### Acceptance criteria

A Kubernetes Role with no access to other Kubernetes resources.

### Would you like to support us?

- [ ] Yes, I would like to support you

**Comment by zachcasper** [comment]
We need:

1. A Role definition YAML scoped to the radius-system namespace
2. An example RoleBinding for tying that to an authenticated user
3. A short tutorial on how this would work with AKS and Entra ID

**Comment by zachcasper** [comment]
For #1, from @willdavsmith 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-cluster-role
rules:
- apiGroups: ["api.ucp.dev"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-access-binding
subjects:
- kind: ServiceAccount
  name: dev-user
  namespace: radius-system
roleRef:
  kind: ClusterRole
  name: aggregator-cluster-role
  apiGroup: rbac.authorization.k8s.io
```
